plugins {
    id 'base'
    id 'org.jetbrains.kotlin.jvm' version '2.2.21' apply false
}

def sharedProps = new Properties()
file('../zmusic.properties').withInputStream { sharedProps.load(it) }

def projectVersion = sharedProps.getProperty('modVersion')
def projectGroup = sharedProps.getProperty('modGroup')

allprojects {
    group = projectGroup
    version = projectVersion

    repositories {
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
            metadataSources {
                mavenPom()
                artifact()
            }
        }
        maven {
            name = 'Modrinth'
            url = 'https://api.modrinth.com/maven'
            content {
                includeGroup 'maven.modrinth'
            }
        }
        mavenLocal()
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.jetbrains.kotlin.jvm'

    dependencies {
        implementation "me.zhenxin:zmusic-shared:${rootProject.version}"
    }

    def modId = sharedProps.getProperty('modId')
    def modName = sharedProps.getProperty('modName')
    def modAuthor = sharedProps.getProperty('modAuthor')
    def modDescription = sharedProps.getProperty('modDescription')
    def modHomepageUrl = sharedProps.getProperty('modHomepageUrl')

    tasks.named('processResources', ProcessResources) {
        inputs.property 'modVersion', project.version

        filesMatching('mcmod.info') {
            expand(
                    modId         : modId,
                    modName       : modName,
                    modAuthor     : modAuthor,
                    modDescription: modDescription,
                    modHomepageUrl: modHomepageUrl,
                    modVersion    : project.version
            )
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}
