pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "zmusic-mod"

include("zmusic-core")
include(
        "zmusic-fabric",
        "zmusic-fabric:zmusic-fabric-1.21.11",
        "zmusic-fabric:zmusic-fabric-1.21.5",
        "zmusic-fabric:zmusic-fabric-1.20.6",
        "zmusic-fabric:zmusic-fabric-1.20.4",
        "zmusic-fabric:zmusic-fabric-1.20.1",
        "zmusic-fabric:zmusic-fabric-1.19.4",
        "zmusic-fabric:zmusic-fabric-1.19.2",
        "zmusic-fabric:zmusic-fabric-1.18.2",
        "zmusic-fabric:zmusic-fabric-1.17.1",
        "zmusic-fabric:zmusic-fabric-1.16.5",
        "zmusic-fabric:zmusic-fabric-1.15.2",
        "zmusic-fabric:zmusic-fabric-1.14.4"
)

include(
        "zmusic-forge",
        "zmusic-forge:zmusic-forge-1.20.1",
        "zmusic-forge:zmusic-forge-1.19.4",
        "zmusic-forge:zmusic-forge-1.19.2",
        "zmusic-forge:zmusic-forge-1.18.2",
        "zmusic-forge:zmusic-forge-1.17.1",
        "zmusic-forge:zmusic-forge-1.16.5",
        "zmusic-forge:zmusic-forge-1.15.2",
        "zmusic-forge:zmusic-forge-1.14.4",
        "zmusic-forge:zmusic-forge-1.12.2"
)

include(
        "zmusic-neoforge",
        "zmusic-neoforge:zmusic-neoforge-1.20.4",
        "zmusic-neoforge:zmusic-neoforge-1.20.6",
        "zmusic-neoforge:zmusic-neoforge-1.21.10",
        "zmusic-neoforge:zmusic-neoforge-1.21.11"
)
