# Mod
modId=zmusic
modName=ZMusic
modVersion=5.0.0-dev
modDescription=A cross-loader Minecraft client mod for music playback.
modAuthor=ZhenXin
modLicense=GPL-3.0

# URLs
modHomepageUrl=https://github.com/zmusic-dev/zmusic-mod
modSourcesUrl=https://github.com/zmusic-dev/zmusic-mod
modIssueUrl=https://github.com/zmusic-dev/zmusic-mod/issues

# Build
modGroup=me.zhenxin
playerVersion=1.0.0-alpha.2
