# Mod
modId=zmusic
modName=ZMusic
modVersion=5.0.0-dev
modDescription=A cross-loader Minecraft client mod for music playback.
modAuthor=ZhenXin
modLicense=GPL-3.0

# URLs
modHomepageUrl=https://github.com/zmusic-dev/zmusic-client
modSourcesUrl=https://github.com/zmusic-dev/zmusic-client
modIssueUrl=https://github.com/zmusic-dev/zmusic-client/issues

# Build
modGroup=me.zhenxin
