plugins {
    id 'net.neoforged.gradle.userdev' version '7.1.38'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation "net.neoforged:neoforge:20.4.251"

    implementation project(":zmusic-core")
}

jar {
    dependsOn(":zmusic-core:jar")
    manifest {
        attributes 'MixinConfigs': 'zmusic.mixins.json'
    }
}
