modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/RealHeart/ZMusic/issues"

[[mods]]
modId = "zmusic"
version = "${version}"
displayName = "ZMusic Mod"
description = "Powerful Music System"
displayURL = "https://m.zplu.cc"
authors = "ZhenXin"

[[dependencies.zmusic]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.zmusic]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "CLIENT"
