modLoader="javafml"
loaderVersion="[1,)"
license="${modLicense}"
issueTrackerURL="${modIssueUrl}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthor}"
description='${modDescription}'
displayURL="${modHomepageUrl}"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[21.1.221,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
