plugins {
    id 'net.minecraftforge.gradle' version '7.0.28'
    id 'net.minecraftforge.renamer' version '1.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

minecraft {
    mappings channel: 'snapshot', version: '20200514-1.15.1'
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:1.15.2-31.2.57')
    implementation project(":zmusic-core")
}

jar {
    dependsOn(":zmusic-core:jar")
}
