plugins {
    id 'net.minecraftforge.gradle' version '7.0.27'
    id 'net.minecraftforge.renamer' version '1.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

minecraft {
    mappings channel: 'official', version: '1.20.4'
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:1.20.4-49.2.7")
    implementation project(":zmusic-core")
}

jar {
    dependsOn(":zmusic-core:jar")
}
