pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "zmusic-mod-26"

include("zmusic-core")
project(":zmusic-core").projectDir = file("../zmusic-core")

include("zmusic-fabric-26.1")
project(":zmusic-fabric-26.1").projectDir = file("../zmusic-fabric/zmusic-fabric-26.1")

include("zmusic-neoforge-26.1")
project(":zmusic-neoforge-26.1").projectDir = file("../zmusic-neoforge/zmusic-neoforge-26.1")
