modLoader = "javafml"
loaderVersion = "[31,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/zmusic-dev/zmusic-mod/issues"
[[mods]]
modId = "zmusic"
version = "${version}"
displayName = "ZMusic"
description = "${description}"
displayURL = "https://zmusic.zhenxin.me"
authors = "ZhenXin"
[[dependencies.zmusic]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.zmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15,1.16)"
ordering = "NONE"
side = "CLIENT"
