plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
}

def sharedProps = new Properties()
file('../zmusic.properties').withInputStream { sharedProps.load(it) }

group = sharedProps.getProperty('modGroup')
version = sharedProps.getProperty('modVersion')

description = 'Shared constants for ZMusic.'

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'zmusic-shared'
        }
    }
}
