modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/starhui-dev/zmusic-mod/issues"

[[mods]]
modId = "zmusic"
version = "${version}"
displayName = "ZMusic"
logoFile = "icon.png"
description = "${description}"
displayURL = "https://zmusic.zhenxin.me"
authors = "ZhenXin"

[[dependencies.zmusic]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4,20.5)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.zmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.5)"
ordering = "NONE"
side = "CLIENT"
