plugins {
    id("net.fabricmc.fabric-loom") version "1.16.2"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    minecraft("com.mojang:minecraft:26.1.2")
    implementation("net.fabricmc:fabric-loader:0.19.2")
    implementation("net.fabricmc.fabric-api:fabric-api:0.150.0+26.1.2")

    implementation(project(":zmusic-core"))
}

jar {
    dependsOn(":zmusic-core:jar")
}
