modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/zmusic-dev/zmusic-mod/issues"

[[mods]]
modId = "zmusic"
version = "${version}"
displayName = "ZMusic"
logoFile = "icon.png"
description = "${description}"
displayURL = "https://zmusic.zhenxin.me"
authors = "ZhenXin"

[[dependencies.zmusic]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,21.12)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.zmusic]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "CLIENT"
