name: Sync Code

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - "v*"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg "https://zhenxin:${CODEBERG_TOKEN}@codeberg.org/zmusic-dev/zmusic-mod.git"
          git push codeberg refs/remotes/origin/main:refs/heads/main --force
          git push codeberg refs/remotes/origin/dev:refs/heads/dev --force
          git push codeberg --tags --force

      - name: Sync to CNB
        env:
          CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          git remote add cnb "https://cnb:${CNB_TOKEN}@cnb.cool/zmusic-dev/zmusic-mod.git"
          git push cnb refs/remotes/origin/main:refs/heads/main --force
          git push cnb refs/remotes/origin/dev:refs/heads/dev --force
          git push cnb --tags --force
